package com.bdilab.sharedcalendar.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_title
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    private String msgTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_content
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.fk_msg_sender
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    private Integer fkMsgSender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.fk_msg_reciever
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    private Integer fkMsgReciever;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_read
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    private Integer isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.fk_event_id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    private Integer fkEventId;

    private Integer fkEventType;

    public Integer getFkEventType() {
        return fkEventType;
    }

    public void setFkEventType(Integer fkEventType) {
        this.fkEventType = fkEventType;
    }

    public Integer getFkEventId() {
        return fkEventId;
    }

    public void setFkEventId(Integer fkEventId) {
        this.fkEventId = fkEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_title
     *
     * @return the value of message.msg_title
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_title
     *
     * @param msgTitle the value for message.msg_title
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_content
     *
     * @return the value of message.msg_content
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_content
     *
     * @param msgContent the value for message.msg_content
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.fk_msg_sender
     *
     * @return the value of message.fk_msg_sender
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public Integer getFkMsgSender() {
        return fkMsgSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.fk_msg_sender
     *
     * @param fkMsgSender the value for message.fk_msg_sender
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public void setFkMsgSender(Integer fkMsgSender) {
        this.fkMsgSender = fkMsgSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.fk_msg_reciever
     *
     * @return the value of message.fk_msg_reciever
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public Integer getFkMsgReciever() {
        return fkMsgReciever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.fk_msg_reciever
     *
     * @param fkMsgReciever the value for message.fk_msg_reciever
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public void setFkMsgReciever(Integer fkMsgReciever) {
        this.fkMsgReciever = fkMsgReciever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_read
     *
     * @return the value of message.is_read
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_read
     *
     * @param isRead the value for message.is_read
     *
     * @mbg.generated Sun Apr 28 11:12:33 CST 2019
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }
}