package com.bdilab.sharedcalendar.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pswd
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private String userPswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_openid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private String userOpenid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setUserName(String userid) {
        this.userName = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pswd
     *
     * @return the value of user.user_pswd
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public String getUserPswd() {
        return userPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pswd
     *
     * @param userPswd the value for user.user_pswd
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setUserPswd(String userPswd) {
        this.userPswd = userPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_openid
     *
     * @return the value of user.user_openid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public String getUserOpenid() {
        return userOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_openid
     *
     * @param userOpenid the value for user.user_openid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setUserOpenid(String userOpenid) {
        this.userOpenid = userOpenid;
    }
}