package com.bdilab.sharedcalendar.model;

import java.util.Date;

public class UuidRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_share_log.id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_share_log.fk_type_id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private Integer fkTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_share_log.fk_subscriber_id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private Integer fkSubscriberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_share_log.uuid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_share_log.is_used
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private int isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_share_log.expire_time
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_share_log.id
     *
     * @return the value of uuid_share_log.id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_share_log.id
     *
     * @param id the value for uuid_share_log.id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_share_log.fk_type_id
     *
     * @return the value of uuid_share_log.fk_type_id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public Integer getFkTypeId() {
        return fkTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_share_log.fk_type_id
     *
     * @param fkTypeId the value for uuid_share_log.fk_type_id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setFkTypeId(Integer fkTypeId) {
        this.fkTypeId = fkTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_share_log.fk_subscriber_id
     *
     * @return the value of uuid_share_log.fk_subscriber_id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public Integer getFkSubscriberId() {
        return fkSubscriberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_share_log.fk_subscriber_id
     *
     * @param fkSubscriberId the value for uuid_share_log.fk_subscriber_id
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setFkSubscriberId(Integer fkSubscriberId) {
        this.fkSubscriberId = fkSubscriberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_share_log.uuid
     *
     * @return the value of uuid_share_log.uuid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_share_log.uuid
     *
     * @param uuid the value for uuid_share_log.uuid
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_share_log.is_used
     *
     * @return the value of uuid_share_log.is_used
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public int getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_share_log.is_used
     *
     * @param isUsed the value for uuid_share_log.is_used
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setIsUsed(int isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_share_log.expire_time
     *
     * @return the value of uuid_share_log.expire_time
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_share_log.expire_time
     *
     * @param expireTime the value for uuid_share_log.expire_time
     *
     * @mbg.generated Sat Mar 30 15:00:05 CST 2019
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
}